/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package centro_de_distribuicao;

/**
 *
 * @author desen
 */
public class INTEFACE_USUARIO extends javax.swing.JPanel {

    /**
     * Creates new form INTEFACE_USUARIO
     */
    public INTEFACE_USUARIO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Adiciona_Exclui = new javax.swing.JButton();
        Exibir = new javax.swing.JButton();

        Adiciona_Exclui.setText("Adiciona/Excluir");
        Adiciona_Exclui.setAlignmentY(0.0F);
        Adiciona_Exclui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adiciona_ExcluiActionPerformed(evt);
            }
        });

        Exibir.setText("Exibir");
        Exibir.setAlignmentY(0.0F);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Exibir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Adiciona_Exclui, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(Adiciona_Exclui)
                .addGap(18, 18, 18)
                .addComponent(Exibir)
                .addGap(93, 93, 93))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Adiciona_ExcluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adiciona_ExcluiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Adiciona_ExcluiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adiciona_Exclui;
    private javax.swing.JButton Exibir;
    // End of variables declaration//GEN-END:variables
}
